In [238]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression    
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import  RobustScaler,MinMaxScaler,StandardScaler
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder
from category_encoders import TargetEncoder
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score

In [239]:
df=pd.read_csv('loan_approval_dataset.csv')

In [240]:
df.head()

,Age,Salary,Credit_Score,Loan_Amount,Loan_Term,Employment_Status,Residence_Type,Previous_Default,Loan_Approved
0,56,136748,584,38209,36 months,Employed,Owned,Yes,Yes
1,46,25287,815,27424,24 months,Self-Employed,Rented,No,Yes
2,32,146593,398,42396,12 months,Unemployed,Rented,Yes,Yes
3,60,54387,696,11370,24 months,Unemployed,Owned,No,No
4,25,28512,788,14528,12 months,Employed,Owned,No,No

In [241]:
x=df.drop(columns='Loan_Approved')
y=df['Loan_Approved']

In [242]:
df['Loan_Term'].unique()

array(['36 months', '24 months', '12 months', '48 months'], dtype=object)

In [243]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

In [244]:
encoder=LabelEncoder()

In [245]:
updated_ytrain=encoder.fit_transform(ytrain)
updated_ytest=encoder.transform(ytest)

In [246]:
encoder=OneHotEncoder()

In [247]:
updated_xtrain=encoder.fit_transform(xtrain[['Residence_Type','Previous_Default','Employment_Status','Loan_Term']])  # It accepts 2-D.

In [248]:
updated_xtrain

<800x12 sparse matrix of type '<class 'numpy.float64'>'
	with 3200 stored elements in Compressed Sparse Row format>

In [249]:
df['Residence_Type'].unique()

array(['Owned', 'Rented', 'Mortgage'], dtype=object)

In [250]:
df['Previous_Default'].unique()

array(['Yes', 'No'], dtype=object)

In [251]:
df['Employment_Status'].unique()

array(['Employed', 'Self-Employed', 'Unemployed'], dtype=object)

In [252]:
updated_xtest=encoder.transform(xtest[['Residence_Type','Previous_Default','Employment_Status','Loan_Term']])

In [253]:
model=LinearRegression()

In [254]:
model.fit(updated_xtrain,updated_ytrain)

LinearRegression()

In [255]:
ytrain_pred=model.predict(updated_xtrain)

In [256]:
r2_score(updated_ytrain,ytrain_pred)

0.006806822202578555

In [257]:
df

,Age,Salary,Credit_Score,Loan_Amount,Loan_Term,Employment_Status,Residence_Type,Previous_Default,Loan_Approved
0,56,136748,584,38209,36 months,Employed,Owned,Yes,Yes
1,46,25287,815,27424,24 months,Self-Employed,Rented,No,Yes
2,32,146593,398,42396,12 months,Unemployed,Rented,Yes,Yes
3,60,54387,696,11370,24 months,Unemployed,Owned,No,No
4,25,28512,788,14528,12 months,Employed,Owned,No,No
...,...,...,...,...,...,...,...,...,...
995,22,49241,500,41020,24 months,Self-Employed,Owned,No,Yes
996,40,116214,423,12415,48 months,Self-Employed,Owned,No,Yes
997,27,64569,300,28155,36 months,Self-Employed,Rented,Yes,Yes
998,61,31745,490,48884,12 months,Self-Employed,Mortgage,No,Yes
999,19,46029,815,21964,24 months,Employed,Mortgage,Yes,No

In [258]:
df=df[['Employment_Status','Residence_Type','Previous_Default','Loan_Approved']]

In [259]:
# import pandas as pd

# df = pd.DataFrame({
#     'Residence_Type': ['Owned', 'Rented', 'Owned', 'Rented', 'Owned', 'Rented'],
#     'Employment_Status': ['Employed', 'Self-Employed', 'Unemployed', 'Employed', 'Self-Employed', 'Employed'],
#     'Previous_Default': ['No', 'Yes', 'No', 'No', 'Yes', 'No'],
#     'Loan_Approved': [1, 0, 1, 1, 0, 1]   # numeric target
# })

# df

In [260]:
df

    Employment_Status Residence_Type Previous_Default Loan_Approved
0            Employed          Owned              Yes           Yes
1       Self-Employed         Rented               No           Yes
2          Unemployed         Rented              Yes           Yes
3          Unemployed          Owned               No            No
4            Employed          Owned               No            No
..                ...            ...              ...           ...
995     Self-Employed          Owned               No           Yes
996     Self-Employed          Owned               No           Yes
997     Self-Employed         Rented              Yes           Yes
998     Self-Employed       Mortgage               No           Yes
999          Employed       Mortgage              Yes            No

[1000 rows x 4 columns]

In [261]:
x=df.drop(columns='Loan_Approved')
y=df['Loan_Approved']

In [262]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

## Label Encoder

In [266]:
# encoder=LabelEncoder()

In [ ]:
# updated_xtrain=encoder.fit_transform(xtrain['Employment_Status'])
# # updated_xtrain=encoder.fit_transform(ytrain)  # It accepts 1-D (mostly we use labelencoder() for target column)
# updated_xtrain

In [268]:
# Unknown Values
# new_input=['Employed','Self-Employed']
# # new_input=['Employed','Self-Employed',"Not Employed"]   # Error --> becoz 'Not Employed'  is unknown label.
# encoder.transform(new_input)

In [269]:
# updated_xtest=encoder.transform(xtest['Employment_Status'])
# updated_xtest

## OneHot Encoder

In [ ]:
encoder=OneHotEncoder()                        # By default handle_unknown='error'.
encoder=OneHotEncoder(handle_unknown='ignore')   # To handle the  unknown values 

# encoder=OneHotEncoder(sparse_output=True)     # sparse output message. default it is True
# encoder=OneHotEncoder(sparse_output=False)      # returns array of values.

# updated_xtrain=encoder.fit_transform(xtrain)
# updated_xtrain

In [271]:
updated_xtrain=encoder.fit_transform(xtrain)
# updated_xtrain=encoder.fit_transform(xtrain['Employment_Status'])   # --> Error becoz expected to pass 2-D 

# updated_xtrain.shape

values=updated_xtrain.toarray()        # --> To check the vlues

columns=encoder.get_feature_names_out()    # --> returns the column names

In [272]:
pd.DataFrame(values,columns=columns)      # To check how the values are transformed in xtrain

,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed,Residence_Type_Mortgage,Residence_Type_Owned,Residence_Type_Rented,Previous_Default_No,Previous_Default_Yes
0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
795,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
796,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
797,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
798,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
799,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0

In [ ]:
# Handle Unknown Values 
# new_input=[['Employed','Self-Employed'],['Owned','Mortgage']]  # Error becoz same no.of cols must be present.

# new_input=[['Employed','Self-Employed',"Not Employed"],['Owned','Mortgage'],['No','Yes']]   # Error --> ("Not Employed") unknown label

new_input=[['Employed','Self-Employed',"Not Employed"],['Owned','Mortgage','Mortgage'],['No','Yes','No']]  # NO Error becoz handle_unknown='ignore' 
updated_xtest=encoder.transform(new_input)

updated_xtest.toarray()    

# For unknown values it assigns zeros (i.e, 0., 0., 0.)

c:\Users\chand\anaconda3\Edunet\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.]])

In [274]:
updated_xtest=encoder.transform(xtest)
# updated_xtest=encoder.transform(xtest[['Employment_Status','Residence_Type']]) # The feature names should match those that were passed during fit.

updated_xtest.shape

values=updated_xtest.toarray()
values 

# columns=encoder.get_feature_names_out           # Not passible

array([[0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 1., 0., ..., 1., 0., 1.],
       ...,
       [0., 0., 1., ..., 1., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.]])

## Ordinal Encoder

In [ ]:
# Without order
encoder=OrdinalEncoder()

In [288]:
updated_xtrain=encoder.fit_transform(xtrain)
# updated_xtrain=encoder.fit_transform(xtrain['Employment_Status'])  # Error becoz it accepts 2-D.
updated_xtrain

array([[1., 2., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [2., 2., 0.],
       [2., 0., 0.],
       [1., 0., 0.]])

In [283]:
columns=encoder.get_feature_names_out()

In [286]:
pd.DataFrame(updated_xtrain,columns=columns)

     Employment_Status  Residence_Type  Previous_Default
0                  1.0             2.0               0.0
1                  0.0             0.0               0.0
2                  0.0             0.0               0.0
3                  0.0             0.0               1.0
4                  2.0             0.0               0.0
..                 ...             ...               ...
795                0.0             2.0               0.0
796                1.0             0.0               1.0
797                2.0             2.0               0.0
798                2.0             0.0               0.0
799                1.0             0.0               0.0

[800 rows x 3 columns]

In [295]:
# new_input=[['Employed','Self-Employed',"Not Employed"],['Owned','Mortgage','Mortgage'],['No','Yes','No']]  # Error becoz unknown labels are present.

new_input=[['Employed','Owned','No'],['Self-Employed','Mortgage','Yes']] 

encoder.transform(new_input)

c:\Users\chand\anaconda3\Edunet\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0., 1., 0.],
       [1., 0., 1.]])

In [290]:
updated_xtest=encoder.transform(xtest)
updated_xtest

array([[1., 0., 0.],
       [2., 0., 0.],
       [1., 2., 1.],
       [0., 2., 0.],
       [2., 2., 0.],
       [0., 1., 1.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 1.],
       [2., 0., 0.],
       [2., 2., 0.],
       [2., 2., 0.],
       [0., 1., 1.],
       [2., 2., 1.],
       [1., 2., 0.],
       [1., 1., 0.],
       [2., 1., 0.],
       [2., 1., 0.],
       [0., 0., 1.],
       [2., 0., 1.],
       [2., 0., 0.],
       [0., 1., 1.],
       [0., 2., 0.],
       [2., 0., 0.],
       [1., 2., 0.],
       [2., 0., 1.],
       [0., 2., 0.],
       [2., 0., 1.],
       [2., 1., 1.],
       [1., 2., 0.],
       [2., 1., 1.],
       [0., 1., 1.],
       [2., 0., 0.],
       [1., 0., 0.],
       [2., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.],
       [2., 0., 0.],
       [2., 1., 1.],
       [0., 1., 0.],
       [1., 2., 1.],
       [2., 0., 1.],
       [2., 1., 0.],
       [0., 2., 0.],
       [2., 2., 1.],
       [2., 1., 0.],
       [0., 1., 0.],
       [2., 0., 0.],
       [2., 2., 1.],
       [2., 2., 0.],
       [2., 0., 0.],
       [2., 1., 0.],
       [0., 2., 0.],
       [1., 2., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 2., 0.],
       [1., 1., 1.],
       [1., 2., 1.],
       [1., 1., 1.],
       [0., 2., 1.],
       [2., 2., 1.],
       [2., 0., 1.],
       [2., 0., 0.],
       [1., 2., 0.],
       [1., 1., 0.],
       [1., 2., 1.],
       [1., 1., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 0., 0.],
       [2., 1., 1.],
       [1., 1., 0.],
       [2., 2., 0.],
       [0., 0., 0.],
       [2., 1., 0.],
       [1., 0., 0.],
       [1., 1., 1.],
       [0., 2., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [2., 1., 1.],
       [2., 0., 1.],
       [1., 0., 1.],
       [1., 0., 0.],
       [0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.],
       [2., 0., 0.],
       [1., 0., 1.],
       [0., 2., 1.],
       [0., 0., 0.],
       [2., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [2., 2., 1.],
       [0., 2., 1.],
       [2., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [2., 2., 1.],
       [1., 2., 0.],
       [0., 1., 0.],
       [1., 2., 0.],
       [0., 0., 0.],
       [2., 2., 0.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 0., 1.],
       [1., 1., 0.],
       [2., 1., 0.],
       [2., 2., 1.],
       [0., 1., 0.],
       [2., 1., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [0., 1., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       [0., 0., 0.],
       [1., 2., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 2., 0.],
       [1., 1., 0.],
       [0., 0., 1.],
       [1., 2., 1.],
       [0., 0., 1.],
       [2., 0., 0.],
       [1., 1., 1.],
       [1., 1., 0.],
       [1., 0., 0.],
       [2., 1., 0.],
       [2., 2., 1.],
       [2., 2., 1.],
       [1., 2., 1.],
       [1., 0., 0.],
       [1., 1., 0.],
       [2., 2., 1.],
       [0., 2., 0.],
       [1., 2., 1.],
       [2., 0., 0.],
       [2., 2., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [1., 2., 0.],
       [1., 0., 1.],
       [0., 2., 1.],
       [2., 0., 1.],
       [2., 2., 0.],
       [0., 2., 0.],
       [2., 1., 0.],
       [1., 1., 0.],
       [2., 2., 1.],
       [0., 2., 0.],
       [1., 1., 0.],
       [0., 0., 0.],
       [0., 2., 0.],
       [0., 2., 1.],
       [1., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [2., 1., 1.],
       [1., 2., 0.],
       [0., 2., 0.],
       [2., 1., 0.],
       [0., 0., 1.],
       [2., 2., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 1., 1.],
       [1., 0., 1.],
       [1., 2., 0.],
       [2., 2., 0.],
       [2., 2., 0.],
       [2., 1., 0.],
       [0., 1., 0.],
       [2., 2., 0.],
       [2., 1., 0.],
       [0., 2., 1.],
       [1., 1., 0.],
       [2., 2., 1.],
       [1., 2., 1.],
       [0., 2., 0.],
       [0., 0., 0.],
       [2., 2., 1.],
       [2., 0., 0.],
       [2., 1., 0.],
       [1., 0., 0.],
       [2., 1., 0.],
       [0., 0., 1.],
       [2., 1., 0.],
       [2., 0., 0.],
       [0., 0., 1.],
       [2., 2., 1.],
       [2., 0., 1.],
       [0., 1., 0.]])

In [ ]:
# Handle Unknown values or labels

encoder=OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)   # if any unknown value is assign then it gives -1.
# we should not use 0 for unknown_value becoz ordinal_encoder assigns values from 0.

In [299]:
updated_xtrain=encoder.fit_transform(xtrain)
updated_xtrain

array([[1., 2., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [2., 2., 0.],
       [2., 0., 0.],
       [1., 0., 0.]])

In [300]:
cols=encoder.get_feature_names_out()

In [304]:
xtrain

    Employment_Status Residence_Type Previous_Default
29      Self-Employed         Rented               No
535          Employed       Mortgage               No
695          Employed       Mortgage               No
557          Employed       Mortgage              Yes
836        Unemployed       Mortgage               No
..                ...            ...              ...
106          Employed         Rented               No
270     Self-Employed       Mortgage              Yes
860        Unemployed         Rented               No
435        Unemployed       Mortgage               No
102     Self-Employed       Mortgage               No

[800 rows x 3 columns]

In [308]:
new_input=[['Employed','Owned','No'],['Self-Employed','Mortgage','No Yes'],["Not Employed",'Mortgage','No']]  

encoder.transform(new_input)

c:\Users\chand\anaconda3\Edunet\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[ 0.,  1.,  0.],
       [ 1.,  0., -1.],
       [-1.,  0.,  0.]])

In [314]:
xtrain

    Employment_Status Residence_Type Previous_Default
29      Self-Employed         Rented               No
535          Employed       Mortgage               No
695          Employed       Mortgage               No
557          Employed       Mortgage              Yes
836        Unemployed       Mortgage               No
..                ...            ...              ...
106          Employed         Rented               No
270     Self-Employed       Mortgage              Yes
860        Unemployed         Rented               No
435        Unemployed       Mortgage               No
102     Self-Employed       Mortgage               No

[800 rows x 3 columns]

In [334]:
xtrain['Previous_Default'].unique()

array(['No', 'Yes'], dtype=object)

In [372]:
# With order
# encoder=OrdinalEncoder(categories=[['Employed','Self-Employed','Unemployed']],handle_unknown='use_encoded_value',unknown_value=-1)
'''
xtrain is having 3 cols and categories having only one column ,So that columns are mismatched so error occured.
'''

# encoder=OrdinalEncoder(categories=[['Employed','Self-Employed','Unemployed'],['Mortgage','Rented','Owned'],['NO','Yes']],handle_unknown='use_encoded_value',unknown_value=-1)
'''  
    Error : Equal no.of unique values must be there.
'''


encoder=OrdinalEncoder(categories=[['Employed','Self-Employed','Unemployed'],['Mortgage','Rented','Owned'],['NO','Yes']],handle_unknown='use_encoded_value',unknown_value=-1)

In [373]:
updated_xtrain=encoder.fit_transform(xtrain)
updated_xtrain

# updated_xtrain=encoder.fit_transform(xtrain[['Employment_Status']])        # No Error always cols and categories should match.
# updated_xtrain

array([[ 1.,  1., -1.],
       [ 0.,  0., -1.],
       [ 0.,  0., -1.],
       ...,
       [ 2.,  1., -1.],
       [ 2.,  0., -1.],
       [ 1.,  0., -1.]])

In [371]:
updated_xtest=encoder.transform(xtest)
updated_xtest

array([[ 1.,  0., -1.],
       [ 2.,  0., -1.],
       [ 1.,  1.,  1.],
       [ 0.,  1., -1.],
       [ 2.,  1., -1.],
       [ 0.,  2.,  1.],
       [ 0.,  2., -1.],
       [ 0.,  0., -1.],
       [ 0.,  0., -1.],
       [ 1.,  0.,  1.],
       [ 2.,  0., -1.],
       [ 2.,  1., -1.],
       [ 2.,  1., -1.],
       [ 0.,  2.,  1.],
       [ 2.,  1.,  1.],
       [ 1.,  1., -1.],
       [ 1.,  2., -1.],
       [ 2.,  2., -1.],
       [ 2.,  2., -1.],
       [ 0.,  0.,  1.],
       [ 2.,  0.,  1.],
       [ 2.,  0., -1.],
       [ 0.,  2.,  1.],
       [ 0.,  1., -1.],
       [ 2.,  0., -1.],
       [ 1.,  1., -1.],
       [ 2.,  0.,  1.],
       [ 0.,  1., -1.],
       [ 2.,  0.,  1.],
       [ 2.,  2.,  1.],
       [ 1.,  1., -1.],
       [ 2.,  2.,  1.],
       [ 0.,  2.,  1.],
       [ 2.,  0., -1.],
       [ 1.,  0., -1.],
       [ 2.,  0.,  1.],
       [ 1.,  2., -1.],
       [ 1.,  2.,  1.],
       [ 2.,  0., -1.],
       [ 2.,  2.,  1.],
       [ 0.,  2., -1.],
       [ 1.,  1.,  1.],
       [ 2.,  0.,  1.],
       [ 2.,  2., -1.],
       [ 0.,  1., -1.],
       [ 2.,  1.,  1.],
       [ 2.,  2., -1.],
       [ 0.,  2., -1.],
       [ 2.,  0., -1.],
       [ 2.,  1.,  1.],
       [ 2.,  1., -1.],
       [ 2.,  0., -1.],
       [ 2.,  2., -1.],
       [ 0.,  1., -1.],
       [ 1.,  1.,  1.],
       [ 1.,  2.,  1.],
       [ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  2.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  2.,  1.],
       [ 0.,  1.,  1.],
       [ 2.,  1.,  1.],
       [ 2.,  0.,  1.],
       [ 2.,  0., -1.],
       [ 1.,  1., -1.],
       [ 1.,  2., -1.],
       [ 1.,  1.,  1.],
       [ 1.,  2., -1.],
       [ 2.,  1., -1.],
       [ 0.,  1., -1.],
       [ 0.,  1., -1.],
       [ 0.,  0., -1.],
       [ 2.,  2.,  1.],
       [ 1.,  2., -1.],
       [ 2.,  1., -1.],
       [ 0.,  0., -1.],
       [ 2.,  2., -1.],
       [ 1.,  0., -1.],
       [ 1.,  2.,  1.],
       [ 0.,  1., -1.],
       [ 0.,  0., -1.],
       [ 0.,  0., -1.],
       [ 2.,  2.,  1.],
       [ 2.,  0.,  1.],
       [ 1.,  0.,  1.],
       [ 1.,  0., -1.],
       [ 0.,  2.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0., -1.],
       [ 2.,  0., -1.],
       [ 1.,  0.,  1.],
       [ 0.,  1.,  1.],
       [ 0.,  0., -1.],
       [ 2.,  0., -1.],
       [ 1.,  0., -1.],
       [ 1.,  0., -1.],
       [ 2.,  1.,  1.],
       [ 0.,  1.,  1.],
       [ 2.,  0., -1.],
       [ 1.,  0., -1.],
       [ 0.,  0., -1.],
       [ 2.,  1.,  1.],
       [ 1.,  1., -1.],
       [ 0.,  2., -1.],
       [ 1.,  1., -1.],
       [ 0.,  0., -1.],
       [ 2.,  1., -1.],
       [ 2.,  2.,  1.],
       [ 2.,  2.,  1.],
       [ 2.,  0.,  1.],
       [ 1.,  2., -1.],
       [ 2.,  2., -1.],
       [ 2.,  1.,  1.],
       [ 0.,  2., -1.],
       [ 2.,  2., -1.],
       [ 1.,  0., -1.],
       [ 1.,  2., -1.],
       [ 0.,  2.,  1.],
       [ 2.,  2.,  1.],
       [ 1.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0., -1.],
       [ 1.,  1., -1.],
       [ 1.,  0.,  1.],
       [ 1.,  0.,  1.],
       [ 1.,  1., -1.],
       [ 1.,  2., -1.],
       [ 0.,  0.,  1.],
       [ 1.,  1.,  1.],
       [ 0.,  0.,  1.],
       [ 2.,  0., -1.],
       [ 1.,  2.,  1.],
       [ 1.,  2., -1.],
       [ 1.,  0., -1.],
       [ 2.,  2., -1.],
       [ 2.,  1.,  1.],
       [ 2.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  0., -1.],
       [ 1.,  2., -1.],
       [ 2.,  1.,  1.],
       [ 0.,  1., -1.],
       [ 1.,  1.,  1.],
       [ 2.,  0., -1.],
       [ 2.,  1.,  1.],
       [ 2.,  2.,  1.],
       [ 1.,  0.,  1.],
       [ 1.,  1., -1.],
       [ 1.,  0.,  1.],
       [ 0.,  1.,  1.],
       [ 2.,  0.,  1.],
       [ 2.,  1., -1.],
       [ 0.,  1., -1.],
       [ 2.,  2., -1.],
       [ 1.,  2., -1.],
       [ 2.,  1.,  1.],
       [ 0.,  1., -1.],
       [ 1.,  2., -1.],
       [ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 0.,  1.,  1.],
       [ 1.,  0.,  1.],
       [ 1.,  0., -1.],
       [ 1.,  0., -1.],
       [ 2.,  2.,  1.],
       [ 1.,  1., -1.],
       [ 0.,  1., -1.],
       [ 2.,  2., -1.],
       [ 0.,  0.,  1.],
       [ 2.,  1.,  1.],
       [ 0.,  2., -1.],
       [ 1.,  0., -1.],
       [ 1.,  2.,  1.],
       [ 1.,  0.,  1.],
       [ 1.,  1., -1.],
       [ 2.,  1., -1.],
       [ 2.,  1., -1.],
       [ 2.,  2., -1.],
       [ 0.,  2., -1.],
       [ 2.,  1., -1.],
       [ 2.,  2., -1.],
       [ 0.,  1.,  1.],
       [ 1.,  2., -1.],
       [ 2.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 0.,  1., -1.],
       [ 0.,  0., -1.],
       [ 2.,  1.,  1.],
       [ 2.,  0., -1.],
       [ 2.,  2., -1.],
       [ 1.,  0., -1.],
       [ 2.,  2., -1.],
       [ 0.,  0.,  1.],
       [ 2.,  2., -1.],
       [ 2.,  0., -1.],
       [ 0.,  0.,  1.],
       [ 2.,  1.,  1.],
       [ 2.,  0.,  1.],
       [ 0.,  2., -1.]])

## Target Encoder

In [362]:
# encoder=TargetEncoder()

# encoder=TargetEncoder(cols=['Employment_Status'])
'''
when we have mixed column names(numeric and categorical)  we use this "cols"1 parameter. 
'''

encoder=TargetEncoder(cols=['Employment_Status'],handle_unknown='value')
'''
Default handle_unknown = 'error'
handle_unknown = 'value' --> Here,"value" works taking average of all the target column and assign it to unknown labels or values. 
'''

'\nDefault handle_unknown = \'error\'\nhandle_unknown = \'value\' --> Here,"value" works taking average of all the target column and assign it to unknown labels or values. \n'

In [363]:
updated_xtrain=encoder.fit_transform(xtrain,ytrain)
updated_xtrain

     Employment_Status Residence_Type Previous_Default
29            0.537594         Rented               No
535           0.490119       Mortgage               No
695           0.490119       Mortgage               No
557           0.490119       Mortgage              Yes
836           0.483986       Mortgage               No
..                 ...            ...              ...
106           0.490119         Rented               No
270           0.537594       Mortgage              Yes
860           0.483986         Rented               No
435           0.483986       Mortgage               No
102           0.537594       Mortgage               No

[800 rows x 3 columns]

In [ ]:
# new_input
# new_input=[['Self-Employed','Rented','No']]
# encoder.transform(new_input)
''' 
KeyError: 'Employment_Status'
Becoz It cannot understand for which column it has to transfer the values.
'''

new_input=pd.DataFrame({'Employment_Status':['Self-Employed'],
                        'Residence_Type':['Rented'],
                        'Previous_Default':['No']}) 
encoder.transform(new_input)
'''
No Error becoz it can understand which column to transfer the values.
'''

   Employment_Status Residence_Type Previous_Default
0           0.537594         Rented               No

In [ ]:
# encoder.transform(xtest)

     Employment_Status  Residence_Type  Previous_Default
521           0.537594        0.481752          0.524155
737           0.483986        0.481752          0.524155
740           0.537594        0.519380          0.481865
660           0.490119        0.519380          0.524155
411           0.483986        0.519380          0.524155
..                 ...             ...               ...
408           0.483986        0.481752          0.524155
332           0.490119        0.481752          0.481865
208           0.483986        0.519380          0.481865
613           0.483986        0.481752          0.481865
78            0.490119        0.511194          0.524155

[200 rows x 3 columns]

## How to seperate numeric and categorical columns

In [ ]:
cat_col=xtrain.select_dtypes(include='object').columns  
cat_col

# num_col=xtrain.select_dtypes(include='number').columns 
# num_col

Index([], dtype='object')